version: 2
jobs:
  build:
    working_directory: ~/Open-MBEE/mdk
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: davidwillard/circleci-oracle-jdk8
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: java -version
    # Dependency caching
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - gradle-repo-v4_0_0-{{ .Branch }}-{{ checksum "gradle.properties" }}
          - gradle-repo-v4_0_0-{{ .Branch }}-
          - gradle-repo-v4_0_0-

    - run: ./gradlew dependencies

    - save_cache:
        paths:
          - ~/.gradle
        key: gradle-repo-v4_0_0--{{ .Branch }}-{{ checksum "gradle.properties" }}

    # Compile
    - run: xvfb-run ./gradlew -PbuildNumber=$CIRCLE_BUILD_NUM -PbuildAccess=opensource -PbuildTag=$CIRCLE_TAG --refresh-dependencies --info --stacktrace clean assemble

    # Test
    - run: xvfb-run ./gradlew -PbuildAccess=opensource -PbuildNumber=$CIRCLE_BUILD_NUM -PbuildTag=$CIRCLE_TAG -PmagicDrawLicense=$MAGICDRAW_LICENSE --info --stacktrace test

    - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - run: find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
    - run: '[ ! -d build/reports ] || cp -R build/reports $CIRCLE_ARTIFACTS/'

    #Deployment
    - deploy:
        command: |
          if [[ "${CIRCLE_TAG}" =~ [0-9.]+(-(a|b|rc)[0-9]+)? ]]; then
            echo "Deploy to artifactory"
            echo "Deploy to Bintray"
          elif [[ "${CIRCLE_BRANCH}" =~ ((release|hotfix|support)/[0-9.]+(-(a|b|rc)[0-9]+)?|master|develop) ]]; then
            echo "Deploy to artifactory"
          else
            echo "Don't deploy"
          fi

      # Teardown
      # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
      # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results