version: 2
jobs:
  build:
    working_directory: ~/Open-MBEE/mdk
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: davidwillard/circleci-oracle-jdk8
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: java -version
    # Dependency caching
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - gradle-repo-v4_0_0-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
          - gradle-repo-v4_0_0-{{ .Branch }}-
          - gradle-repo-v4_0_0-

    - run: ./gradlew dependencies

    - save_cache:
        paths:
          - ~/.gradle
        key: gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}

    # Compile
    #   This would typically go in either a build or a build-and-test job when using workflows
    # This is based on your 1.0 configuration file or project settings
    - run: xvfb-run ./gradlew -PbuildNumber=$CIRCLE_BUILD_NUM -PbuildAccess=opensource -PbuildTag=$CIRCLE_TAG --refresh-dependencies --info --stacktrace clean assemble
    # Test
    #   This would typically be a build job when using workflows, possibly combined with build
    # This is based on your 1.0 configuration file or project settings
    - run: xvfb-run ./gradlew -PbuildAccess=opensource -PbuildNumber=$CIRCLE_BUILD_NUM -PbuildTag=$CIRCLE_TAG -PmagicDrawLicense=$MAGICDRAW_LICENSE --info --stacktrace test
    # This is based on your 1.0 configuration file or project settings
    - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - run: find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
    - run: '[ ! -d build/reports ] || cp -R build/reports $CIRCLE_ARTIFACTS/'
    # Deployment
    # Your existing circle.yml file contains deployment steps.
    # The config translation tool does not support translating deployment steps
    # since deployment in CircleCI 2.0 are better handled through workflows.
    # See the documentation for more information https://circleci.com/docs/2.0/workflows/
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
